language: java
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
  - psql -d testing_db
  - psql "CREATE TABLE testing_db.public.test_table (id SERIAL PRIMARY KEY, comment VARCHAR);"

  - echo "Before scripting phase"
  - echo -e "\033[42mTest DB with user\\=foo and password\\=bar was succesfully created"

script:
 - mvn clean package

after_script:
 - echo -e "\033[42mScript finished"

after_success:
 - echo -e "\033[42mBuild was successful. $TRAVIS_TEST_RESULT"

after_failure:
 - echo "Build was failed"

