language: java
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
#  - psql -d testing_db -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - psql -d testing_db -c "CREATE TABLE testing_db.public.test_table (id SERIAL PRIMARY KEY, comment VARCHAR);" -U postgres
  - psql -d testing_db -c "CREATE UNIQUE INDEX test_table_id_uindex ON testing_db.public.test_table (id);" -U postgres
#  - psql -d testing_db -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "test";" -U postgres
  - echo "Before scripting phase"
  - echo -e "\033[42mTest DB with user\\=foo and password\\=bar was succesfully created"

script:
 - mvn clean package

after_script:
 - echo -e "\033[42mScript finished"

after_success:
 - echo -e "\033[42mBuild was successful. $TRAVIS_TEST_RESULT"

after_failure:
 - echo "Build was failed"

