language: java
services:
  - postgresql
  - docker

before_script:
  - psql -f ./target/classes/scripts/init_test_env.sql -U postgres
  - echo "Before scripting phase"
  - echo -e "\033[42mTest DB with user\\=foo and password\\=bar was succesfully created"

script:
 - mvn clean package

after_script:
 - echo -e "\033[42mScript finished"

befor install:
# - docker build -t scherbinin/app .
# - docker run -p 8090:8090 scherbinin/app

after_success:
 - echo -e "\033[42mBuild was successful. $TRAVIS_TEST_RESULT"

after_failure:
 - docker build -t scherbinin/app .
 - echo "Build was failed"

