language: java
services:
  - postgresql
  - docker

before_script:
  - psql -f ./target/classes/scripts/init_test_env.sql -U postgres
  - echo "Before scripting phase"
  - echo -e "\033[42mTest DB with user\\=foo and password\\=bar was succesfully created"

script:
 - mvn clean package

after_script:
 - echo -e "\033[42mScript finished"

befor install:
# - docker build -t scherbinin/app .
# - docker run -p 8090:8090 scherbinin/app

after_success:
 - echo -e "\033[42mBuild and tests successfully complete"
 - echo -e "\033[42mDocker stuff start"
 - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
 - docker build -t scherbinin/java_spring_hibernate .
 docker push java_spring_hibernate
 - echo -e "\033[42mContainer deploy was successfully done"

after_failure:
 - echo "Build was failed"

