language: java
services:
  - postgresql

before_script:
  - psql -f src/scripts/testdb_init.sql
  - echo "Before scripting phase"
  - echo -e "\033[42mTest DB with user\\=foo and password\\=bar was succesfully created"

script:
 - mvn clean package

after_script:
 - echo -e "\033[42mScript finished"

after_success:
 - echo -e "\033[42mBuild was successful. $TRAVIS_TEST_RESULT"

after_failure:
 - echo "Build was failed"

